[project]
name = "transversal-star-compilation"
version = "0.1.0"
description = "A Python project for simulating rotation performance in quantum systems."
authors = [
    { name = "Wan-Hsuan Lin", email = "wanhsuanlin@g.ucla.edu" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "imageio>=2.35.1",
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.13.3",
    "scipy>=1.10.1",
    "simpy>=4.1.1",
    "sortedcontainers>=2.4.0",
    "stim>=1.15.0",
    "sympy>=1.13.3",
]

[tool.setuptools]
packages = ["src"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=24.0",
    "mypy>=1.0"
]
